stages:
  data_preparation:
    cmd: python stages/data_preparation.py --config=params.yaml
    deps:
      - stages/data_preparation.py
    params:
      - base
      - data_preparation
    outs:
      - ${base.data_dir}/X_train.pkl
      - ${base.data_dir}/X_test.pkl
      - ${base.data_dir}/y_train.pkl
      - ${base.data_dir}/y_test.pkl
  model_training:
    cmd: python stages/model_training.py --config=params.yaml
    deps:
      - stages/model_training.py
      - ${base.data_dir}/X_train.pkl
      - ${base.data_dir}/y_train.pkl
    params:
      - base
      - train
    outs:
      - ${train.model_dir}/${train.model_fname}
  covariate_drift_detector_training:
    cmd: python stages/covariate_drift_detector_training.py --config=params.yaml
    deps:
      - stages/covariate_drift_detector_training.py
      - ${base.data_dir}/X_train.pkl
    params:
      - base
      - detector
    outs:
      - ${detector.dir}/${detector.data_drift.fname}
  evaluation:
    cmd: python stages/evaluation.py --config=params.yaml
    deps:
      - stages/evaluation.py
      - ${base.data_dir}/X_test.pkl
      - ${base.data_dir}/y_test.pkl
      - ${train.model_dir}/${train.model_fname}
      - ${detector.dir}/${detector.data_drift.fname}
    params:
      - base
      - detector
      - train
      - evaluation
    metrics:
      - ${evaluation.metrics_dir}/ml.json:
          cache: false
      - ${evaluation.metrics_dir}/data_drift.json:
          cache: false
    plots:
      - ${evaluation.plots_dir}/temp_feature_distribution.png:
          cache: false
      - ${evaluation.plots_dir}/hum_feature_distribution.png:
          cache: false