base:
  data_dir: data/bike-sharing
  data_fname: hour.csv
  random_state: 5

data_preparation:
  test_size: 0.33
  data_split: random

train:
  model_dir: models
  model_fname: ML_bike_sharing
  n_estimators: 50

detector:
  dir: models
  data_drift:
    fname: covariate_shift_detector.joblib

evaluation:
  metrics_dir: metrics
  plots_dir: plots
