base:
  data_dir: data/bike-sharing
  data_fname: hour.csv
  random_state: 5

data_preparation:
  test_size: 0.33
  data_split: random

train:
  model_dir: models
  model_fname: pipe.joblib
  n_estimators: 50

detector:
  dir: models
  data_drift:
    fname: detector.joblib
  concept_drift:
    fname_working: cd_detector_wrk.joblib
    fname_noworking: cd_detector_nowrk.joblib
    latent_dim_working: 48
    latent_dim_noworking: 12

evaluation:
  metrics_dir: metrics
  plots_dir: plots
